language: generic

jdk:
  - openjdk6
  - oraclejdk6

cache:
  directories:
    - "$HOME/.m2/repository"

script:
  # boot repeater console
  - cd ./bin
  - rm -rf ${HOME}/sandbox ${HOME}/.sandbox-module
  - nohup sh ./bootstrap.sh > ${HOME}/repeater-bootstrap.log &
  - sh ./health.sh
  - cd -

after_success:
  - mvn clean cobertura:cobertura
  - kill -9 $(ps -ef | grep "repeater-bootstrap.jar" | grep "java" | grep -v grep | awk '{print $2}')
  - bash <(curl -s https://codecov.io/bash)